baseURL = "https://grenoble-meetups.fr"
locale = "fr-FR"
defaultContentLanguage = "fr"
title = "Grenoble Tech Meetups"
enableRobotsTXT = true
enableGitInfo = true
buildFuture = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[taxonomies]

[params]
  description = "Retrouvez tous les meetups tech de Grenoble : développement, agilité, data, design, jeux vidéo, et plus encore. Agenda collaboratif de la communauté tech grenobloise."
